name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - name: Setup Python
    uses: actions/setup-python@v2.3.2
    with:
      # Version range or exact version of a Python version to use, using SemVer's version range syntax.
      python-version: # optional, default is 3.x
      # Used to specify a package manager for caching in the default directory. Supported values: pip, pipenv.
      cache: # optional
      # The target architecture (x86, x64) of the Python interpreter.
      architecture: # optional
      # Used to pull python distributions from actions/python-versions. Since there's a default, this is typically not supplied by the user.
      token: # optional, default is ${{ github.token }}
      # Used to specify the path to dependency files. Supports wildcards or a list of file names for caching multiple dependencies.
      cache-dependency-path: # optional
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
